services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: learning_language
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d learning_language" ]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@pg:5432/learning_language"
    restart: unless-stopped


networks:
  app-network:
    driver: bridge



volumes:
  pgdata:
