"""Switch to func.now() timestamps

Revision ID: 4d2ce756aa22
Revises: cad3f4858c43
Create Date: 2025-10-22 19:37:37.123464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d2ce756aa22"
down_revision: Union[str, None] = "cad3f4858c43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
